### ISSUE TITLE
Mod incompatibility

### ISSUE THREAD

**Issue by CCCClear** [Dplayend/Just-Leveling#16]
In the latest version of 1.18.2forge, this mod is incompatible with the Unidentified Enchantments mod. 
https://www.curseforge.com/minecraft/mc-mods/unidentified-enchantments
The game crashes when interacting with items in the chest that require enchatments identification.

**Comment by VirtualGaming1** [comment]
he will need the crash log and the log file as well

**Comment by CCCClear** [comment]
Of course
[crash-2023-11-06_10.58.05-client.txt](https://github.com/Dplayend/Just-Leveling/files/13262008/crash-2023-11-06_10.58.05-client.txt)
[latest.log](https://github.com/Dplayend/Just-Leveling/files/13262009/latest.log)
