### ISSUE TITLE
SUGERENCIA

### ISSUE THREAD

**Issue by d-rick** [Dplayend/Just-Leveling#2]
Me encanta tu mod, por sugerir que podría haber compatibilidad con otros mods al hacer que las skills afecten a armaduras y herramientas de cualquier otro mod.

no se de programación, no se si es posible por medio de un tag "#armor" o "#tool" pero seria increíble que sin importar los mods que pongas las skills afecte a todo.

solo una sugerencia, disculpa mi ignorancia.

**Comment by Dplayend** [comment]
si lo hacen, solo tienes que añadirlo en la configuracion del mod, estoy haciendo en la wiki como añadir items que necesiten requerimientos, tambien voy añadir una compatibilidad con [cloth config](https://legacy.curseforge.com/minecraft/mc-mods/cloth-config), asi se podria editar mejor el config

**Comment by Dplayend** [comment]
aqui esta por si te sirve, recuerda instalar el mod que deje arriba, tambien el mod esta en el lenguaje español españa, hablo español por cierto
![2023-10-18_03 46 29](https://github.com/Dplayend/Just-Leveling/assets/69760998/8abc2b79-39c9-481a-a731-8c86d8fc986c)
