### ISSUE TITLE
CRASH 

### ISSUE THREAD

**Issue by d-rick** [Dplayend/Just-Leveling#3]
MINECRAFT: 1.20.1
FORGE: 47.2.1
MOD VERSION: Just Leveling Forge 1.20.x - v1.3
[crash-2023-10-18_11.01.16-server.txt](https://github.com/Dplayend/Just-Leveling/files/13030948/crash-2023-10-18_11.01.16-server.txt)

**Comment by Dplayend** [comment]
just delete just_leveling-common.toml from config folder
