### ISSUE TITLE
Can't find attribute justleveling:block_reach

### ISSUE THREAD

**Issue by ceifadorcinixtru** [Dplayend/Just-Leveling#4]
When i try to load or make a new world, this message appears: java.lang.IllegalArgumentException: Can't find attribute justleveling:block_reach

I didnt change or add anything in the configs, i just have installed the mod.

[crash-2023-10-18_13.37.10-client.txt](https://github.com/Dplayend/Just-Leveling/files/13031240/crash-2023-10-18_13.37.10-client.txt)

**Comment by ceifadorcinixtru** [comment]
The mod that was causing the crash was UnionLib.

**Comment by Dplayend** [comment]
Fixed the issue with block_reach in the v1.6, sorry for the late
https://legacy.curseforge.com/minecraft/mc-mods/just-leveling/files/4810299
