### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by wsxiya** [Dplayend/Just-Leveling#7]
Launching the game using the "Sinytra Connector" to load the "Bosses of Mass Destruction" mod causes the game to crash
[crash-2023-10-22_12.48.52-client.txt](https://github.com/Dplayend/Just-Leveling/files/13062392/crash-2023-10-22_12.48.52-client.txt)

**Comment by Dplayend** [comment]
you have a mod who affects LivingEntity.class with mixins, thats why the game crash

**Comment by wsxiya** [comment]
> 你有一个影响 LivingEntity 的模组.class与混合，这就是游戏崩溃的原因

How to solve this?

**Comment by Dplayend** [comment]
find the mod who affects the LivingEntity.class and tell the mod loader to put { }, in the mixins like these:
![image](https://github.com/Dplayend/Just-Leveling/assets/69760998/ea74ee9e-23ae-43ea-a8f6-8eb15508a5d7)

**Comment by Dplayend** [comment]
no, my bad, i see the issue, i going to fixed in the v1.6

**Comment by wsxiya** [comment]
> 不，我的错，我看到了问题，我将在v1.6中修复

Thanks

**Comment by Dplayend** [comment]
Fixed, thanks for notice me the issue
https://legacy.curseforge.com/minecraft/mc-mods/just-leveling/files/4809896

**Comment by wsxiya** [comment]
> Fixed, thanks for notice me the issue https://legacy.curseforge.com/minecraft/mc-mods/just-leveling/files/4809896

The game still crashes using v1.6

**Comment by wsxiya** [comment]
[crash-2023-10-22_15.59.18-client.txt](https://github.com/Dplayend/Just-Leveling/files/13062683/crash-2023-10-22_15.59.18-client.txt)
