### ISSUE TITLE
v1.6 still crashes

### ISSUE THREAD

**Issue by wsxiya** [Dplayend/Just-Leveling#8]
Sorry, I raised this issue again, the game still crashes when I use v1.6 version
[crash-2023-10-22_15.59.18-client.txt](https://github.com/Dplayend/Just-Leveling/files/13063072/crash-2023-10-22_15.59.18-client.txt)

**Comment by wsxiya** [comment]
The following is my mod list. When one of "BOMD" or "justleveling" is deleted, the game can start normally.
![{SF3%NRRZMN}K4J277YPTQI](https://github.com/Dplayend/Just-Leveling/assets/114494454/7647c087-9b08-4f47-a9de-8a9c63256511)

**Comment by Dplayend** [comment]
but just leveling is a forge version, not fabric

**Comment by wsxiya** [comment]
> 但只是调平是锻造版本，而不是织物

I used the "Sinytra Connector" mod

**Comment by Dplayend** [comment]
try to contact to the BOMD and thell him to update all his mixin classes and put it { } in @Mixin
for example this is has to be @Mixin({ServerPlayerEntity.class})
![image](https://github.com/Dplayend/Just-Leveling/assets/69760998/ea4f0fdf-c8b9-4311-b845-7727631f44a3)

**Comment by wsxiya** [comment]
> 尝试联系 BOMD 并让他更新他所有的 mixin 类并将其放入 { } 例如，这必须是 （{ServerPlayerEntity.class}） ![图像](https://user-images.githubusercontent.com/69760998/277179326-ea4f0fdf-c8b9-4311-b845-7727631f44a3.png)

“Marium's Soulslike Weaponry”This problem also occurs

**Comment by Dplayend** [comment]
and again, the fact with the { } is that it allows there to be multiple mixin
![image](https://github.com/Dplayend/Just-Leveling/assets/69760998/b1162ad7-8973-4b78-9c2f-056a389868a1)

**Comment by Dplayend** [comment]
here is my mixin, to avoid colliding with other mods I added { } in the @mixin and in the method
![image](https://github.com/Dplayend/Just-Leveling/assets/69760998/c141ba85-350f-4e10-9488-85cd526d4a09)

**Comment by wsxiya** [comment]
> here is my mixin, to avoid colliding with other mods I added { } in the @mixin and in the method ![image](https://user-images.githubusercontent.com/69760998/277180189-f098601d-4b28-4256-8e9d-63370fa7cb7d.png)

Okay, I will go there to give feedback. I am a novice and can’t understand the code.

**Comment by Dplayend** [comment]
Fixed in the v1.7
